import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from './header'
import Main from './main'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>VWCL</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/icon.png"/>
            </Head>

            <Header/>
            <Main/>

        </div>
    )
}
